import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { PS1 } from "../../components";
import "./Help.css";
function Help({ option }) {
    if (option.length === 0) {
        return (_jsx(_Fragment, { children: _jsxs("div", { className: "help__AjX7", children: [_jsxs("div", { className: "bannerCommandLine__AjX7", children: [_jsx(PS1, {}), _jsx("input", { className: "bannerInput__AjX7", disabled: true, value: "help" })] }), _jsxs("div", { children: [_jsx("h3", { className: "helpCommandsTitle__AjX7", children: "[ Welcome to the Yesod System's help utility! ]" }), _jsx("table", { className: "helpCommandsTable__AjX7", children: _jsxs("tbody", { children: [_jsxs("tr", { children: [_jsx("td", { className: "helpCommandsTableHeaderCol__AjX7", children: "help [?arguments]" }), _jsx("td", { children: "List permissible commands and return more about a specific command" })] }), _jsxs("tr", { children: [_jsx("td", { className: "helpCommandsTableHeaderCol__AjX7", children: "fetchsum" }), _jsx("td", { children: "Display on terminal a summary of my website" })] }), _jsxs("tr", { children: [_jsx("td", { className: "helpCommandsTableHeaderCol__AjX7", children: "projects" }), _jsx("td", { children: "View a list of the projects I've worked on" })] }), _jsxs("tr", { children: [_jsx("td", { className: "helpCommandsTableHeaderCol__AjX7", children: "whoami" }), _jsx("td", { children: "Get more insight about the creator of this website" })] }), _jsxs("tr", { children: [_jsx("td", { className: "helpCommandsTableHeaderCol__AjX7", children: "experience" }), _jsx("td", { children: "Examine my professional history" })] }), _jsxs("tr", { children: [_jsx("td", { className: "helpCommandsTableHeaderCol__AjX7", children: "email" }), _jsx("td", { children: "Open your default email client and let's talk" })] }), _jsxs("tr", { children: [_jsx("td", { className: "helpCommandsTableHeaderCol__AjX7", children: "download [arguments]" }), _jsx("td", { children: "Download a specific file from my website" })] }), _jsxs("tr", { children: [_jsx("td", { className: "helpCommandsTableHeaderCol__AjX7", children: "open [arguments]" }), _jsx("td", { children: "Open a new tab to view a specific link" })] }), _jsxs("tr", { children: [_jsx("td", { className: "helpCommandsTableHeaderCol__AjX7", children: "banner" }), _jsx("td", { children: "Display the terminal header" })] }), _jsxs("tr", { children: [_jsx("td", { className: "helpCommandsTableHeaderCol__AjX7", children: "echo [arguments]" }), _jsx("td", { children: "Write formatted text and display on the terminal" })] }), _jsxs("tr", { children: [_jsx("td", { className: "helpCommandsTableHeaderCol__AjX7", children: "clear" }), _jsx("td", { children: "Refresh the terminal" })] })] }) })] })] }) }));
    }
    else if (option.length === 1 && option[0] === "download") {
        return (_jsx(_Fragment, { children: _jsxs("div", { className: "downloadHelpCommand__AjX7", children: [_jsxs("div", { className: "bannerCommandLine__AjX7", children: [_jsx(PS1, {}), _jsx("input", { className: "bannerInput__AjX7", disabled: true, value: `help ${option[0]}` })] }), _jsxs("div", { className: "downloadHelpContent__AjX7", children: [_jsx("p", { style: { marginBottom: "14px" }, children: "Usage: download [argument]" }), _jsx("table", { className: "downloadHelpCommandTable__AjX7", children: _jsxs("tbody", { children: [_jsx("tr", { children: _jsx("td", { className: "helpCommandsTableHeaderCol__AjX7", children: "Arguments" }) }), _jsxs("tr", { children: [_jsx("td", { className: "helpCommandsTableHeaderCol__AjX7", children: "resume" }), _jsx("td", { children: "Download a virus-free PDF copy of my resume into your local device." })] })] }) })] })] }) }));
    }
    else if (option.length === 1 && option[0] === "open") {
        return (_jsx(_Fragment, { children: _jsxs("div", { className: "openHelpCommand__AjX7", children: [_jsxs("div", { className: "bannerCommandLine__AjX7", children: [_jsx(PS1, {}), _jsx("input", { className: "bannerInput__AjX7", disabled: true, value: `help ${option[0]}` })] }), _jsxs("div", { className: "openHelpCommandContent__AjX7", children: [_jsx("p", { style: { marginBottom: "14px" }, children: "Usage: open [arguments]" }), _jsx("table", { className: "openHelpCommandTable__AjX7", children: _jsxs("tbody", { children: [_jsx("tr", { children: _jsx("td", { children: "Arguments" }) }), _jsxs("tr", { children: [_jsx("td", { children: "github" }), _jsx("td", { children: "Open my Github profile on a new tab and learn more about what I work on" })] }), _jsxs("tr", { children: [_jsx("td", { children: "twitter" }), _jsx("td", { children: "Open my Twitter profile on a new tab and know more about who am I as a person" })] }), _jsxs("tr", { children: [_jsx("td", { children: "linkedin" }), _jsx("td", { children: "Open my LinkedIn profile on a new tab and connect with me for professional opportunities" })] }), _jsxs("tr", { children: [_jsx("td", { children: "email" }), _jsx("td", { children: "Open your default client and tap me on the shoulder!" })] })] }) })] })] }) }));
    }
    else {
        return (_jsx(_Fragment, { children: _jsxs("div", { className: "commandExecutionError__AjX7", children: [_jsxs("div", { className: "bannerCommandLine__AjX7", children: [_jsx(PS1, {}), _jsx("input", { className: "bannerInput__AjX7", disabled: true, value: `help ${option.join(" ")}` })] }), _jsx("div", { children: _jsx("p", { className: "bannerContentPar__AjX7", children: "The aforementioned \"help\" command contain(s) invalid argument(s). Please enter \"help\" to--why do I keep repeating myself?" }) })] }) }));
    }
}
export default Help;
